name: Deploy

on:
  push:
    branches:
    - main

jobs:
  build:
    run-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.11
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ira-cd-ci"
          heroku_email: "taylor.strubhar@gmail.com"